plugins {
    id 'com.android.application'
}

def runNumber = (System.getenv("GITHUB_RUN_NUMBER") ?: "1").toInteger()

android {
    namespace 'ru.brucelee3.app'
    compileSdk 34

    defaultConfig {
        applicationId 'ru.brucelee3.app'
        minSdk 24
        targetSdk 34
        versionCode runNumber
        versionName "1.0.${runNumber}"
    }

    signingConfigs {
        release {
            storeFile file('release.keystore')
            storePassword 'brucelee3'
            keyAlias 'brucelee3'
            keyPassword 'brucelee3'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
